name: wordle-hs
version: 0.1.0.0
github: "jozsefsallai/wordle-hs"
license: MIT
author: "József Sallai"
maintainer: "sallai.jozsef@student.ms.sapientia.ro"
copyright: "2022 József Sallai"

extra-source-files:
  - README.md

synopsis: Wordle for the command line
description: Command line version of the popular Wordle game, written in Haskell.

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - code-page
  - file-embed
  - split
  - time
  - random
  - aeson
  - directory

library:
  source-dirs: src

executables:
  wordle-hs-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wordle-hs
